sudo: required
services:
  - docker


before_install:
  - docker build -t migot01/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run migot01/react-test npm test -- --coverage

after_success:
  - docker build -t migot01/multi-client ./client
  - docker build -t migot01/multi-server ./server
  - docker build -t migot01/multi-worker ./worker
  - docker build -t migot01/multi-nginx ./nginx
# Log in to the docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Take those images and push them to docker hub
  - docker push migot01/multi-client
  - docker push migot01/multi-server
  - docker push migot01/multi-worker
  - docker push migot01/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-052149296376
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
